name: Trigger auto deployment for gateway services

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ dev ]
    paths:
      - 'src/Gateway/**'
      - '.github/workflows/gateway-cicd.yml'

  # Allow mannually trigger 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DEV_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.DEV_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.DEV_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DEV_CONTAINER_REGISTRY_URL }}/gateway:${{ github.sha }}
          file: ./src/Gateway/Dockerfile
          context: ./