name: Trigger auto deployment for ordering services

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ dev, staging, prod ]
    paths:
      - 'src/Ordering/**'
      - '.github/workflows/ordering-cicd.yml'

  # Allow mannually trigger 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%s')"
        
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/ordering:${{ github.ref_name }}-${{ github.sha }}-${{ steps.timestamp.outputs.timestamp }}
          file: ./src/Ordering/Dockerfile
          context: ./